before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$DEMO_PVKEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SMP_YPM_1_SEPANJANG_PVKEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SMA_WH_2_TAMAN_PVKEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$SMK_YPM_1_TAMAN_PVKEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEMO_SERVER >> ~/.ssh/known_hosts
    - ssh-keyscan $SMP_YPM_1_SEPANJANG_SERVER >> ~/.ssh/known_hosts
    - ssh-keyscan $SMA_WH_2_TAMAN_SERVER >> ~/.ssh/known_hosts
    - ssh-keyscan $SMK_YPM_1_TAMAN_SERVER >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

deploy_to_demo:
    stage: deploy
    only:
        - master
    environment: production
    script:
        - ssh -t root@$DEMO_SERVER "cd /var/www/diakademik && git pull origin master"

deploy_to_smpypm1sepanjang:
    stage: deploy
    only:
        - latest-release
    environment: production
    script:
        - ssh -t root@$SMP_YPM_1_SEPANJANG_SERVER "cd /var/www/diakademik && git pull origin latest-release"
        - ssh -t root@$SMP_YPM_1_SEPANJANG_SERVER "cd /var/www/diakademik && php artisan migrate"

deploy_to_smawh2taman:
    stage: deploy
    only:
        - latest-release
    environment: production
    script:
        - ssh -t root@$SMA_WH_2_TAMAN_SERVER "cd /var/www/diakademik && git pull origin latest-release"
        - ssh -t root@$SMA_WH_2_TAMAN_SERVER "cd /var/www/diakademik && php artisan migrate"

deploy_to_smkypm1taman:
    stage: deploy
    only:
        - latest-release
    environment: production
    script:
        - ssh -t root@$SMK_YPM_1_TAMAN_SERVER "cd /var/www/diakademik && git pull origin latest-release"
        - ssh -t root@$SMK_YPM_1_TAMAN_SERVER "cd /var/www/diakademik && php artisan migrate"