x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: "50m"
    max-file: 6

x-base: &base
  profiles: [app]
  depends_on:
    mysql:
      condition: service_healthy
    redis:
      condition: service_healthy
  build:
    context: .
    dockerfile: FrankenPHP.Alpine.Dockerfile
    args:
      APP_ENV: 'production' # to load .env.production
      APP_HOST: 'localhost'
      WWWUSER: ${HOST_UID:-1000}
      WWWGROUP: ${HOST_GID:-1000}
  image: laravel/app
  user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
  ulimits:
    nofile:
      soft: 20000
      hard: 40000
  security_opt:
    - no-new-privileges:true
  networks:
    - stack
  volumes:
    - './:/var/www/html'
    - './storage/app/public:/var/www/html/storage/app/public'
    - './storage/logs:/var/www/html/storage/logs'
  logging: *default-logging
  restart: always

services:
  traefik:
    profiles: [app]
    image: traefik:latest
    restart: always
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    security_opt:
      - no-new-privileges:true
    command:
      - "--log.level=WARN"
      - "--ping=true"
      - "--api=true"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.traefik.address=:8190"
      # - "--entryPoints.app.address=:80"
      - "--entryPoints.app.address=:8000"
      # - "--entryPoints.app.http.redirections.entryPoint.to=app-secure"
      # - "--entryPoints.app.http.redirections.entryPoint.scheme=https"
      # - "--entryPoints.app-secure.address=:443"
      # - "--entryPoints.app-secure.http3=true"
      - "--entryPoints.glances.address=:61208"
      - "--entryPoints.netdata.address=:19999"
    ports:
      - "127.0.0.1:8190:8190" # Traefik
      - "127.0.0.1:8000:8000" # PHP Octane
      # - "80:80" # HTTP
      # - "443:443" # HTTPS
      # - "443:443/udp" # HTTP/3
      - "127.0.0.1:61208:61208" # Glances
      - "127.0.0.1:19999:19999" # NetData
    networks:
      - stack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging: *default-logging
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`localhost`) || Host(`localhost`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.entryPoints: traefik
      traefik.http.routers.traefik.middlewares: "traefik-auth,traefik-retry"

      traefik.http.middlewares.traefik-retry.retry.attempts: 4
      traefik.http.middlewares.traefik-retry.retry.initialinterval: 100ms
      traefik.http.middlewares.traefik-auth.basicauth.removeheader: true
      traefik.http.middlewares.traefik-auth.basicauth.users: "user:$$2y$$05$$8zbpsdxg9wDiiKdqxiB0zeAlxZtG68P1SDBOvCN4IooLFewLx70Gm" # user:123456
  app:
    <<: *base
    healthcheck:
      test: [ "CMD", "curl", "--fail", "localhost:8000/up" ]
      interval: 3s
      retries: 12
      timeout: 5s
    labels:
      traefik.enable: true

      traefik.http.routers.app.rule: Host(`localhost`) || Host(`localhost`)
      traefik.http.routers.app.entryPoints: app
      traefik.http.routers.app.service: app-service
      traefik.http.routers.app.middlewares: "redirect-scheme,app-retry,app-compress,security-headers"

      traefik.http.routers.app-secure.rule: Host(`localhost`) || Host(`localhost`)
      traefik.http.routers.app-secure.entryPoints: app-secure
      traefik.http.routers.app-secure.service: app-service
      traefik.http.routers.app-secure.tls: true
      traefik.http.routers.app-secure.middlewares: "redirect-scheme,app-retry,app-compress,security-headers"

      traefik.http.services.app-service.loadbalancer.server.port: 8000 # Because container exposes multiple ports
      traefik.http.services.app-service.loadbalancer.healthCheck.path: "/up"
      traefik.http.services.app-service.loadbalancer.healthCheck.hostname: "localhost"
      traefik.http.services.app-service.loadbalancer.healthCheck.port: 8000
      traefik.http.services.app-service.loadbalancer.healthCheck.interval: 3s
      traefik.http.services.app-service.loadbalancer.healthCheck.timeout: 5s

      traefik.http.middlewares.limit.buffering.maxRequestBodyBytes: 460000000 # 460mb
      # traefik.http.middlewares.redirect-scheme.redirectscheme.scheme: https
      # traefik.http.middlewares.redirect-scheme.redirectscheme.permanent: true
      traefik.http.middlewares.app-retry.retry.attempts: 4
      traefik.http.middlewares.app-retry.retry.initialinterval: 100ms
      traefik.http.middlewares.app-compress.compress: true
      traefik.http.middlewares.security-headers.headers.accesscontrolmaxage: 100
      traefik.http.middlewares.security-headers.headers.addvaryheader: true # Vary: Origin
      traefik.http.middlewares.security-headers.headers.hostsproxyheaders: X-Forwarded-Host
      traefik.http.middlewares.security-headers.headers.stsseconds: 63072000 # Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
      traefik.http.middlewares.security-headers.headers.stsincludesubdomains: true
      traefik.http.middlewares.security-headers.headers.stspreload: true
      traefik.http.middlewares.security-headers.headers.forcestsheader: true
      traefik.http.middlewares.security-headers.headers.customFrameOptionsValue: SAMEORIGIN # X-Frame-Options: same-origin
      traefik.http.middlewares.security-headers.headers.contenttypenosniff: true # X-Content-Type-Options: nosniff
      traefik.http.middlewares.security-headers.headers.browserxssfilter: true # X-XSS-Protection: 1; mode=block
      traefik.http.middlewares.security-headers.headers.referrerpolicy: no-referrer-when-downgrade # Referrer-Policy: no-referrer-when-downgrade
      traefik.http.middlewares.security-headers.headers.permissionspolicy: camera=(), geolocation=(), microphone=(), payment=(), usb=(), interest-cohort=(), gyroscope=()
  redis:
    profiles: [app]
    image: 'redis:alpine'
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command: [ "redis-server", "--requirepass", "123456", "--maxmemory", "2gb" ]
    security_opt:
      - no-new-privileges:true
    volumes:
      - 'stack-redis:/data'
    networks:
      - stack
    logging: *default-logging
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    restart: always
    labels:
      traefik.enable: false
  glances:
    profiles: [administration]
    image: nicolargo/glances:latest-full
    pid: host
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
      - /etc/os-release:/etc/os-release:ro
    environment:
      - "GLANCES_OPT=-w"
      - TZ="UTC"
    networks:
      - stack
    logging: *default-logging
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.glances.rule: Host(`localhost`)
      traefik.http.routers.glances.entryPoints: glances
      traefik.http.routers.glances.middlewares: "glances-auth,glances-retry"
      traefik.http.middlewares.glances-retry.retry.attempts: 4
      traefik.http.middlewares.glances-retry.retry.initialinterval: 100ms
      traefik.http.middlewares.glances-auth.basicauth.removeheader: true
      traefik.http.middlewares.glances-auth.basicauth.users: "user:$$2y$$05$$8zbpsdxg9wDiiKdqxiB0zeAlxZtG68P1SDBOvCN4IooLFewLx70Gm" # user:123456
  mysql:
    profiles: [app]
    image: 'mysql:latest'
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    security_opt:
      - no-new-privileges:true
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'stack-mysql:/var/lib/mysql'
      - '../backup:/backup'
    networks:
      - stack
    healthcheck:
      test: [ "CMD", "mysql", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      interval: 15s
      retries: 12
      timeout: 20s
    restart: always
    logging: *default-logging
    labels:
      traefik.enable: false
      docker-volume-backup.stop-during-backup: true
      docker-volume-backup.archive-pre: /bin/sh -c 'pg_dump -U ${DB_USERNAME} -F t ${DB_DATABASE} > /backup/${DB_DATABASE}-database.tar'
  backup:
    profiles: [administration]
    image: offen/docker-volume-backup:v2
    security_opt:
      - no-new-privileges:true
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_CRON_EXPRESSION: "0 2 * * *" # run every day at 2am
      BACKUP_RETENTION_DAYS: '7'
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    logging: *default-logging
    volumes:
      - stack-mysql:/backup/mysql:ro
      - ../backup/volumes:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: false
  netdata:
    profiles: [administration]
    image: netdata/netdata
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    logging: *default-logging
    networks:
      - stack
    volumes:
      - stack-netdataconfig:/etc/netdata
      - stack-netdatalib:/var/lib/netdata
      - stack-netdatacache:/var/cache/netdata
      # - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.netdata.rule: Host(`localhost`)
      traefik.http.routers.netdata.entryPoints: netdata
      traefik.http.routers.netdata.middlewares: "netdata-auth"
      traefik.http.middlewares.netdata-auth.basicauth.removeheader: true
      traefik.http.middlewares.netdata-auth.basicauth.users: "user:$$2y$$05$$8zbpsdxg9wDiiKdqxiB0zeAlxZtG68P1SDBOvCN4IooLFewLx70Gm" # user:123456
networks:
  stack:
    driver: bridge
volumes:
  stack-redis:
    driver: local
  stack-mysql:
    driver: local
  stack-netdataconfig:
    driver: local
  stack-netdatalib:
    driver: local
  stack-netdatacache:
    driver: local

