x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: "50m"
    max-file: 6

x-base: &base
  profiles: [app]
  depends_on:
    mysql:
      condition: service_healthy
    redis:
      condition: service_healthy
  build:
    context: .
    dockerfile: FrankenPHP.Alpine.Dockerfile
    args:
      APP_ENV: 'production' # to load .env.production
      APP_HOST: 'localhost'
      WWWUSER: ${HOST_UID:-1000}
      WWWGROUP: ${HOST_GID:-1000}
  image: laravel/app
  user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
  ulimits:
    nofile:
      soft: 20000
      hard: 40000
  security_opt:
    - no-new-privileges:true
  ports:
    - '8000:8000'
  networks:
    - stack
  volumes:
    - './:/var/www/html'
    - './storage/app/public:/var/www/html/storage/app/public'
    - './storage/logs:/var/www/html/storage/logs'
  logging: *default-logging
  restart: always

services:
  app:
    <<: *base
    healthcheck:
      test: [ "CMD", "curl", "--fail", "localhost:8000/up" ]
      interval: 3s
      retries: 12
      timeout: 5s
  redis:
    profiles: [app]
    image: 'redis:alpine'
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command: [ "redis-server", "--requirepass", "123456", "--maxmemory", "2gb" ]
    security_opt:
      - no-new-privileges:true
    volumes:
      - 'stack-redis:/data'
    ports:
      - '16379:6379'
    networks:
      - stack
    logging: *default-logging
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    restart: always
  glances:
    profiles: [administration]
    image: nicolargo/glances:latest-full
    pid: host
    security_opt:
      - no-new-privileges:true
    ports:
      - '61208:61208'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
      - /etc/os-release:/etc/os-release:ro
    environment:
      - "GLANCES_OPT=-w"
      - TZ="ID"
    networks:
      - stack
    logging: *default-logging
    restart: always
  mysql:
    profiles: [app]
    image: 'mysql:latest'
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    security_opt:
      - no-new-privileges:true
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'stack-mysql:/var/lib/mysql'
      - '../backup:/backup'
    networks:
      - stack
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-U", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 15s
      retries: 12
      timeout: 20s
    restart: always
    logging: *default-logging
    labels:
      docker-volume-backup.stop-during-backup: true
      docker-volume-backup.archive-pre: /bin/sh -c 'mysql_dump -U ${DB_USERNAME} -F t ${DB_DATABASE} > /backup/${DB_DATABASE}-database.tar'
  backup:
    profiles: [administration]
    image: offen/docker-volume-backup:v2
    security_opt:
      - no-new-privileges:true
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_CRON_EXPRESSION: "0 2 * * *" # run every day at 2am
      BACKUP_RETENTION_DAYS: '7'
    restart: always
    networks:
      - stack
    depends_on:
      mysql:
        condition: service_healthy
    logging: *default-logging
    volumes:
      - stack-mysql:/backup/mysql:ro
      - ../backup/volumes:/archive
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  netdata:
    profiles: [administration]
    image: netdata/netdata
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    ports:
      - '19999:19999'
    logging: *default-logging
    networks:
      - stack
    volumes:
      - stack-netdataconfig:/etc/netdata
      - stack-netdatalib:/var/lib/netdata
      - stack-netdatacache:/var/cache/netdata
      # - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    networks:
      - stack
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks:
  stack:
    driver: bridge
volumes:
  stack-redis:
    driver: local
  stack-mysql:
    driver: local
  stack-netdataconfig:
    driver: local
  stack-netdatalib:
    driver: local
  stack-netdatacache:
    driver: local

