version: 2.1

jobs:
  deploy-to-staging:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy To SERVER DEV
          command: |
            ssh -t $SSH_USER@$SERVER_DEV "cd /var/www/diakademik_demo && git pull origin master && php artisan migrate --force"

  deploy-to-smp-ypm-1:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            ssh -t $SSH_USER@$SGC_1 "cd /var/www/html/smpypm1/diakademik && git pull origin latest-release && php artisan migrate --force && php artisan optimize:clear && php artisan optimize"

  deploy-to-smk-ypm-2:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            ssh -t $SSH_USER@$SGC_1 "cd /var/www/html/smkypm2/diakademik && git pull origin latest-release && php artisan migrate --force && php artisan optimize:clear && php artisan optimize"

  deploy-to-smp-ypm-2:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            ssh -t $SSH_USER@$SGC_1 "cd /var/www/html/smpypm2/diakademik && git pull origin latest-release && php artisan migrate --force && php artisan optimize:clear && php artisan optimize"

  deploy-to-sma-wh-2:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            ssh -t $SSH_USER@$SGC_2 "cd /var/www/html/smawh2/diakademik && git pull origin latest-release && php artisan migrate --force && php artisan optimize:clear && php artisan optimize"

  deploy-to-smk-ypm-1:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            ssh -t $SSH_USER@$SGC_2 "cd /var/www/html/smkypm1/diakademik && git pull origin latest-release && php artisan migrate --force && php artisan optimize:clear && php artisan optimize"

  deploy-to-smk-ypm-3:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            ssh -t $SSH_USER@$SGC_3 "cd /var/www/html/smkypm3/diakademik && git pull origin latest-release && php artisan migrate --force && php artisan optimize:clear && php artisan optimize"

  deploy-to-sma-maryam:
    machine:
      enabled: true
    steps:
      - run:
          command: |
            ssh -t $SSH_USER@$SGC_3 "cd /var/www/html/smamaryam/diakademik && git pull origin latest-release && php artisan migrate --force && php artisan optimize:clear && php artisan optimize"

workflows:
  # to-staging-only-master:
  #   when:
  #     or:
  #       - equal: [master, << pipeline.git.branch >>]
  #   jobs:
  #     - deploy-to-staging

  to-production:
    jobs:
      - deploy-to-smp-ypm-1
      - deploy-to-sma-wh-2
      - deploy-to-smk-ypm-1
      - deploy-to-smk-ypm-2
      - deploy-to-smp-ypm-2
      - deploy-to-smk-ypm-3
      - deploy-to-sma-maryam
